### ISSUE TITLE
 Warning: Undefined array key "transaction" in C:\greco\htdocs\paystack\vendor\yabacon\paystack-php\src\Paystack\Helpers\Router.php on line 100

### ISSUE THREAD

**Issue by Lefagana** [yabacon/paystack-php#36]
Fatal error: Uncaught TypeError: get_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, null given in C:\greco\htdocs\paystack\vendor\yabacon\paystack-php\src\Paystack\Helpers\Router.php:67 Stack trace: #0 C:\greco\htdocs\paystack\vendor\yabacon\paystack-php\src\Paystack\Helpers\Router.php(67): get_class_methods(NULL) #1 C:\greco\htdocs\paystack\vendor\yabacon\paystack-php\src\Paystack.php(106): Yabacon\Paystack\Helpers\Router->__construct('transaction', Object(Yabacon\Paystack)) #2 C:\greco\htdocs\paystack\index.php(13): Yabacon\Paystack->__get('transaction') #3 {main} thrown in C:\greco\htdocs\paystack\vendor\yabacon\paystack-php\src\Paystack\Helpers\Router.php on line 67

**Comment by zeoharlem** [comment]
Hi!
follow this link for the solution
https://github.com/yabacon/paystack-php/blob/master/src/Paystack/Helpers/Router.php

change this private function getRouteClass($paystackObj) to the one in your Router.php helper class..

**Comment by lucthanca** [comment]
I hotfix this by modifying in [Yabacon\Paystack\Helpers\Router:100](https://github.com/yabacon/paystack-php/blob/master/src/Paystack/Helpers/Router.php)
from 
```php
return $paystackObj->custom_routes[$this->route];
```
to
```php
$route = $paystackObj->custom_routes[$this->route];
if ($route === null) {
    return 'Yabacon\\Paystack\\Routes\\' . ucwords($this->route);
}
```

**Comment by damienmckenna** [comment]
That suggests all that's needed is a new stable release of the library?
